# Dependencies
markdown:         kramdown
highlighter:      pygments
remote-theme:     pool/hyde

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lost Letters
tagline:          'Nicht gedruckte Leserbriefe'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              
baseurl:          https://sigasser.github.io/lost-letters/

author:
  name:           'Simon Gasser'
  url:            https://t.me/sigasser

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
